//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MNPOSTEntities : DbContext
    {
        public MNPOSTEntities()
            : base("name=MNPOSTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BS_Contracts> BS_Contracts { get; set; }
        public virtual DbSet<BS_Countries> BS_Countries { get; set; }
        public virtual DbSet<BS_CustomerGroups> BS_CustomerGroups { get; set; }
        public virtual DbSet<BS_Customers> BS_Customers { get; set; }
        public virtual DbSet<BS_Districts> BS_Districts { get; set; }
        public virtual DbSet<BS_Employees> BS_Employees { get; set; }
        public virtual DbSet<BS_PostOffices> BS_PostOffices { get; set; }
        public virtual DbSet<BS_Provinces> BS_Provinces { get; set; }
        public virtual DbSet<BS_Wards> BS_Wards { get; set; }
        public virtual DbSet<BS_Zones> BS_Zones { get; set; }
        public virtual DbSet<MM_Mailers> MM_Mailers { get; set; }
        public virtual DbSet<MM_TroubleTickets> MM_TroubleTickets { get; set; }
        public virtual DbSet<UMS_Functions> UMS_Functions { get; set; }
        public virtual DbSet<UMS_Permissions> UMS_Permissions { get; set; }
        public virtual DbSet<UMS_UserAccounts> UMS_UserAccounts { get; set; }
        public virtual DbSet<UMS_UserGroups> UMS_UserGroups { get; set; }
    }
}
