//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_CommissionOfferDetail
    {
        public string DocumentID { get; set; }
        public string MailerID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Amt4Commission { get; set; }
        public Nullable<double> ComPercent { get; set; }
        public Nullable<double> CommissionAmount { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
