//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_CustomerDebitVoucher
    {
        public string DocumentID { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string PostOfficeID { get; set; }
        public string CustomerGroupID { get; set; }
        public string Description { get; set; }
        public string InvoiceCode { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> LastTime { get; set; }
        public Nullable<double> ToTalAmount { get; set; }
    }
}
