//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_CommissionOffer
    {
        public string DocumentID { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public Nullable<System.DateTime> DocumentTime { get; set; }
        public string PostOfficeID { get; set; }
        public string UserAccountID { get; set; }
        public string CustomerID { get; set; }
        public string RepresentativeID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> TotalAmt4Commission { get; set; }
        public Nullable<double> TotalCommissionAmount { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<double> VATPercent { get; set; }
        public Nullable<double> VATAmount { get; set; }
        public Nullable<double> ComPercent { get; set; }
        public bool IsPayComplete { get; set; }
        public string PayDocumentID { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string PayNotes { get; set; }
        public Nullable<System.DateTime> CommMonth { get; set; }
    }
}
