//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_CustomerDebitVoucherDetail
    {
        public string DocumentID { get; set; }
        public string MailerID { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public decimal Price { get; set; }
        public decimal PriceService { get; set; }
        public decimal DiscountPercent { get; set; }
        public decimal Discount { get; set; }
        public decimal VATpercent { get; set; }
        public decimal BfVATamount { get; set; }
        public decimal VATamount { get; set; }
        public decimal AfVATamount { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public int Quantity { get; set; }
        public decimal Weight { get; set; }
    }
}
