//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_CustomerGroups
    {
        public string CustomerGroupID { get; set; }
        public string CustomerGroupName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CustomerGroupCode { get; set; }
        public string Company { get; set; }
        public string ConatctPhone { get; set; }
        public string ContactEmail { get; set; }
        public string ContactAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string PaymentMethodID { get; set; }
        public Nullable<int> DebitDate { get; set; }
        public Nullable<bool> COD { get; set; }
    }
}
