//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_PartnerMapInfo
    {
        public string Id { get; set; }
        public string PartnerID { get; set; }
        public string FormField { get; set; }
        public string MNPostData { get; set; }
        public string PartnerData { get; set; }
    }
}
