//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_PriceGroups
    {
        public string GroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> ZoneNumber { get; set; }
        public Nullable<int> WeightNumber { get; set; }
    }
}
