//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_Partners
    {
        public string PartnerID { get; set; }
        public string PartnerCode { get; set; }
        public string UserLogin { get; set; }
        public string PassLogin { get; set; }
        public string TokenLogin { get; set; }
        public string ParterName { get; set; }
        public string ParterPhoneSP { get; set; }
        public string PartnerAddress { get; set; }
        public string PostOfficeID { get; set; }
        public Nullable<int> Expired { get; set; }
        public Nullable<System.DateTime> LastModife { get; set; }
        public string UserID { get; set; }
    }
}
