//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_PriceMaTrixs
    {
        public string PriceMatrixID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string PostOfficeID { get; set; }
        public string GroupID { get; set; }
        public string PriceType { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> ApplyAllCustomer { get; set; }
        public string ApplyAllZone { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Service { get; set; }
    }
}
