//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpployeeDebitCOD
    {
        public string Id { get; set; }
        public string MailerID { get; set; }
        public Nullable<double> COD { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> AccountantConfirm { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string DocumentID { get; set; }
        public string EmployeeID { get; set; }
    }
}
