//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_ComissionDinhMuc
    {
        public string ComissionID { get; set; }
        public decimal ValueBegin { get; set; }
        public decimal ValueEnd { get; set; }
        public Nullable<int> ComissionPercent { get; set; }
    }
}
