//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_DiscountPolicys
    {
        public string DiscountID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string PostOfficeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
        public Nullable<bool> AllService { get; set; }
        public Nullable<bool> AllCustomer { get; set; }
        public Nullable<bool> AllProvince { get; set; }
        public Nullable<bool> PermanentCal { get; set; }
        public Nullable<decimal> LimitValue { get; set; }
        public Nullable<int> AllMethod { get; set; }
    }
}
