//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_EmployeeDebitVoucherDetails
    {
        public string DocumentID { get; set; }
        public string MailerID { get; set; }
        public Nullable<decimal> ReciveCOD { get; set; }
        public Nullable<System.DateTime> LastUpDate { get; set; }
        public Nullable<decimal> COD { get; set; }
    }
}
