//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_History
    {
        public string MailerID { get; set; }
        public string StatusID { get; set; }
        public string PostOfficeID { get; set; }
        public string DocumentID { get; set; }
        public System.DateTime DateChange { get; set; }
        public string UserGroupID { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
