//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_MailerServices
    {
        public string MailerID { get; set; }
        public string ServiceID { get; set; }
        public Nullable<decimal> PriceDefault { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> LastUpDate { get; set; }
    }
}
