//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_MailerDeliveryDetail
    {
        public string DocumentID { get; set; }
        public string MailerID { get; set; }
        public string DeliveryTo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> DeliveryStatus { get; set; }
        public string DeliveryNotes { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> ReturnReasonID { get; set; }
    }
}
