//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_MailerPartner
    {
        public string DocumentID { get; set; }
        public string DocumentCode { get; set; }
        public string PartnerID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Notes { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string PostOfficeID { get; set; }
    }
}
