//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_MailerServices
    {
        public string MailerID { get; set; }
        public string ServiceID { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal PriceDefault { get; set; }
        public bool IsPercentage { get; set; }
        public decimal BfVATAmount { get; set; }
        public decimal VATAmount { get; set; }
        public decimal AfVATAmount { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public bool SyncFlag { get; set; }
        public Nullable<System.DateTime> LastSyncDate { get; set; }
    }
}
