//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_PackingList
    {
        public string DocumentID { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string PostOfficeID { get; set; }
        public string PostOfficeIDAccept { get; set; }
        public string NumberOfPackage { get; set; }
        public Nullable<double> Weight { get; set; }
        public string TripNumber { get; set; }
        public Nullable<System.DateTime> ArrivedDate { get; set; }
        public string TransportObjectID { get; set; }
        public string SendDescription { get; set; }
        public string AcceptDescription { get; set; }
        public Nullable<int> PackingListStatus { get; set; }
        public string MailerType { get; set; }
        public string UserGroupSend { get; set; }
        public string UserGroupAccept { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public string EmployeeSend { get; set; }
        public string EmployeeAccept { get; set; }
        public string UserGroupLastModified { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
