//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_RecieveMoney
    {
        public string DocumentID { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string MoneyColector { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> MailerAccount { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public string PostOfficeID { get; set; }
    }
}
