//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_TakeMailers
    {
        public string DocumentID { get; set; }
        public string DocumentCode { get; set; }
        public string Content { get; set; }
        public string UserCreate { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerProvinceID { get; set; }
        public string CustomerDistrictID { get; set; }
        public string CustomerWardID { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string PostID { get; set; }
    }
}
