//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_TrackingPartner
    {
        public string Id { get; set; }
        public string MailerID { get; set; }
        public string StatusID { get; set; }
        public string Describe { get; set; }
        public string LocationCurrent { get; set; }
        public string OrderReferece { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string StatusName { get; set; }
    }
}
