//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_TroubleTicketDetails
    {
        public string TicketID { get; set; }
        public int STT { get; set; }
        public string NoiDung { get; set; }
        public string NguoiNhap { get; set; }
        public string TrangThai { get; set; }
    }
}
