//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_TroubleTickets
    {
        public string TicketID { get; set; }
        public string CustomerID { get; set; }
        public string TicketName { get; set; }
        public Nullable<System.DateTime> TicketDate { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string PostOfficeID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string Contact { get; set; }
    }
}
