//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMS_GroupMenu
    {
        public UMS_GroupMenu()
        {
            this.UMS_Menu = new HashSet<UMS_Menu>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Position { get; set; }
        public string Icon { get; set; }
    
        public virtual ICollection<UMS_Menu> UMS_Menu { get; set; }
    }
}
