//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTCOMMON
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessage
    {
        public string Id { get; set; }
        public string UserID { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Topic { get; set; }
    }
}
