//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTWEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WS_Slider
    {
        public int ID { get; set; }
        public string Image01 { get; set; }
        public string Image02 { get; set; }
        public string Image03 { get; set; }
        public string Caption01 { get; set; }
        public string Caption02 { get; set; }
        public string Caption03 { get; set; }
    }
}
