//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_Contracts
    {
        public string ContractID { get; set; }
        public string CustomerID { get; set; }
        public string RepresentativeID { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string CurrencyID { get; set; }
        public System.DateTime AppendDate { get; set; }
        public byte[] Description { get; set; }
        public string PostOfficeID { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string MemberOf { get; set; }
        public string Note { get; set; }
        public string ContractNo { get; set; }
        public string LastUpdUser { get; set; }
    }
}
