//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTDATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MNPOSTEntities : DbContext
    {
        public MNPOSTEntities()
            : base("name=MNPOSTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<AspNetRole> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public DbSet<AspNetUser> AspNetUsers { get; set; }
        public DbSet<BS_Contracts> BS_Contracts { get; set; }
        public DbSet<BS_Countries> BS_Countries { get; set; }
        public DbSet<BS_CustomerGroups> BS_CustomerGroups { get; set; }
        public DbSet<BS_Customers> BS_Customers { get; set; }
        public DbSet<BS_Districts> BS_Districts { get; set; }
        public DbSet<BS_Employees> BS_Employees { get; set; }
        public DbSet<BS_PostOffices> BS_PostOffices { get; set; }
        public DbSet<BS_Provinces> BS_Provinces { get; set; }
        public DbSet<BS_Wards> BS_Wards { get; set; }
        public DbSet<BS_Zones> BS_Zones { get; set; }
        public DbSet<MM_Mailers> MM_Mailers { get; set; }
        public DbSet<MM_TroubleTickets> MM_TroubleTickets { get; set; }
        public DbSet<UMS_GroupMenu> UMS_GroupMenu { get; set; }
        public DbSet<UMS_Menu> UMS_Menu { get; set; }
        public DbSet<UMS_MenuUser> UMS_MenuUser { get; set; }
        public DbSet<UMS_UserGroups> UMS_UserGroups { get; set; }
    }
}
