//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTWEBSITEMODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MNPOSTWEBSITEEntities : DbContext
    {
        public MNPOSTWEBSITEEntities()
            : base("name=MNPOSTWEBSITEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WS_Contact> WS_Contact { get; set; }
        public virtual DbSet<WS_Post> WS_Post { get; set; }
        public virtual DbSet<WS_Recruitment> WS_Recruitment { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<WS_AboutUs> WS_AboutUs { get; set; }
        public virtual DbSet<WS_ServiceType> WS_ServiceType { get; set; }
        public virtual DbSet<WS_Slider> WS_Slider { get; set; }
    }
}
