//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTWEBSITEMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WS_AboutUs
    {
        public string ID { get; set; }
        public string ContentAbout { get; set; }
    }
}
