//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTWEBSITEMODEL
{
    using System;
    using System.Collections.Generic;
    using System.Text.RegularExpressions;

    public partial class WS_Post
    {
        public int ID { get; set; }
        public string PostName { get; set; }
        public string PostBy { get; set; }
        public string Service { get; set; }
        public string Avatar { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ContentPost { get; set; }

        public string GenerateSlug()
        {
            string phrase = string.Format("{0}-{1}", ID, PostName);

            string str = RemoveAccent(phrase).ToLower();
            // invalid chars           
            str = Regex.Replace(str, @"[^a-z0-9\s-]", "");
            // convert multiple spaces into one space   
            str = Regex.Replace(str, @"\s+", " ").Trim();
            // cut and trim 
            str = str.Substring(0, str.Length <= 45 ? str.Length : 45).Trim();
            str = Regex.Replace(str, @"\s", "-"); // hyphens   
            return str;
        }

        private string RemoveAccent(string text)
        {
            byte[] bytes = System.Text.Encoding.GetEncoding("Cyrillic").GetBytes(text);
            return System.Text.Encoding.ASCII.GetString(bytes);
        }
    }
}
