//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNPOSTWEBSITEMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WS_Post
    {
        public int ID { get; set; }
        public string PostName { get; set; }
        public string PostBy { get; set; }
        public string Service { get; set; }
        public string Avatar { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ContentPost { get; set; }
    }
}
